language: c
cache:
  ccache: true
  directories:
    - reference
compiler:
  - gcc

dist: xenial

os:
  - linux

addons:
  apt:
    update: true
    packages: &required_packages
      - [libnuma-dev, linux-headers-$(uname -r), python3-setuptools, python3-wheel, python3-pip, ninja-build]

aarch64_packages: &aarch64_packages
  - *required_packages
  - [gcc-aarch64-linux-gnu, libc6-dev-arm64-cross, pkg-config-aarch64-linux-gnu]

extra_packages: &extra_packages
  - *required_packages
  - [libbsd-dev, libpcap-dev, libcrypto++-dev, libjansson4, abigail-tools]

before_install: ./.ci/${TRAVIS_OS_NAME}-setup.sh

env:
  - DEF_LIB="shared"

matrix:
  include:
  - env: DEF_LIB="shared" EXTRA_PACKAGES=1 ABI_CHECKS=1
    compiler: gcc
    addons:
      apt:
        packages:
          - *extra_packages
  - env: DEF_LIB="shared" EXTRA_PACKAGES=1 ABI_CHECKS=1
    arch: arm64
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
          - *extra_packages

script: ./.ci/${TRAVIS_OS_NAME}-build.sh
